# Default settings for rq-dashboard

RQ_DASHBOARD_REDIS_URL = ['redis://127.0.0.1:6379']
RQ_DASHBOARD_REDIS_SENTINELS = None
RQ_DASHBOARD_REDIS_MASTER_NAME = None
RQ_DASHBOARD_POLL_INTERVAL = 2500
RQ_DASHBOARD_WEB_BACKGROUND = 'black'
RQ_DASHBOARD_DELETE_JOBS = True
RQ_DASHBOARD_URL_PREFIX = ''
